version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout

      # Build koraci (npr. instalacija zavisnosti, kompilacija, minifikacija)
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Build
          command: npm run build

      # Deploy koraci (prilagodite ovo prema vašim potrebama)
      - run:
          name: Deploy to Production
          command: |
            # Dodajte komande koje su potrebne za deploy
            # Na primer, možete koristiti rsync, scp, ili neki drugi alat

workflows:
  version: 2
  sample:
    jobs:
      - build-and-deploy
