version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      # Dodajte korake za build i deploy prema potrebama vašeg projekta

workflows:
  version: 2
  sample:
    jobs:
      - build-and-deploy
